[build.environment]
  NETLIFY_USE_PNPM = "true"
 NODE_VERSION = "19.5.0"
[build]
  command = "OUTPUT=netlify astro build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
