[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "1.1.11"

[build]
  command = "OUTPUT=netlify astro build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
